

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install --force

      # - name: Build
      #   run: npm run build

      # - name: List Files
      #   run: ls && cd dist && ls 
      
    #   - name: Configure AWS CLI
    #     run: |
    #       mkdir -p ~/.aws
    #       echo "[default]" > ~/.aws/config
    #       echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/config
    #       echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/config
    #       echo "region = us-east-2" >> ~/.aws/config
      
    #   - name: aws s3 delete bucket archives
    #     run: aws s3 rm s3://bucket-name --recursive
      
    #   - name: aws s3 upload archives
    #     run: aws s3 cp ./dist/nombre-de-proyecto s3://bucket-name --recursive


